name: Update Financial Data

on:
  schedule:
    - cron: '0 16 * * *'   # Run daily at 16:00 UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  update-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread oauth2client

      - name: Write service account credentials
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" | base64 -d > service_account.json

      # 🔍 Optional: Debug step to verify the key file is valid (remove after first success)
      - name: Validate service_account.json (debug only)
        run: |
          echo "Validating service_account.json..."
          python -m json.tool service_account.json
        # ⚠️ Remove or comment this step after first run to avoid printing sensitive data

      - name: Run Main Stocks script
        run: python Main_Stocks.py

      - name: Run Historical Stocks script
        run: python HistoricalStocks_gspread.py

      - name: Upload Historical_Stocks.csv as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Historical_Stocks
          path: Historical_Stocks.csv

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated Updates"
          add: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up service account key
        if: always()
        run: |
          shred -u service_account.json || rm -f service_account.json
