name: Update Financial Data

on:
  schedule:
    - cron: '0 16 * * *'   # Daily at 16:00 UTC
  workflow_dispatch:        # Manual trigger

jobs:
  update-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for proper git push/pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread oauth2client

      - name: Write service account credentials
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" | base64 -d > service_account.json

      - name: Run Main Stocks script
        run: python Main_Stocks.py

      - name: Run Historical Stocks script
        run: python HistoricalStocks_gspread.py

      - name: Upload Historical_Stocks.csv as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Historical_Stocks
          path: Historical_Stocks.csv
          if-no-files-found: warn

      - name: Ensure git remote is set
        run: |
          git remote remove origin || true
          git remote add origin https://github.com/${{ github.repository }}

      - name: Commit and push changes (safe)
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated Updates"
          add: |
            Main_Actual_Stock.csv
            Stock_Info.csv
            update-stock-data.yml
            Main_Stocks.py
            HistoricalStocks_gspread.py
            Tickers_Codes.csv
            README.md
          pull: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up secrets
        run: rm service_account.json
