name: Update Financial Data

on:
  schedule:
    - cron: '0 16 * * *'   # Run daily at 16:00 UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  update-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread oauth2client

      - name: Write service account credentials
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" | base64 -di > service_account.json

      - name:   Validate service_account.json (debug only)
        run: |
          echo "Content of service_account.json:"
          cat service_account.json
          echo "Validating JSON format..."
          python -m json.tool service_account.json
        #  Remove this step after confirming JSON is valid

      - name: Run Main Stocks script
        run: python Main_Stocks.py

      - name: Run Historical Stocks script
        run: python HistoricalStocks_gspread.py

      - name: Upload Historical_Stocks.csv as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Historical_Stocks
          path: Historical_Stocks.csv 

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated Updates"
          add: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up secrets
        run: rm service_account.json
