name: Update Financial Data

on:
  schedule:
    - cron: '0 16 * * *'   
  workflow_dispatch:        

jobs:
  update-stock:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repo   
        uses: actions/checkout@v3

      - name: Set up Python   
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Install Dependencies YF   
        run: |
          pip install yfinance pandas

      - name: Running Script   # This executes script and downloads the csv files
        run: python Main_Stocks.py

 
      - name: Running another script # This executes script and downloads the csv files
 
        run: python Historical_Stocks.py
 
      - name: Running Script  2 # This executes script and downloads the csv files
 
        run: python Historical_Stocks.py
 
 

        
      - name: Upload Historical_Stocks.csv as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Historical_Stocks
          path: Historical_Stocks.csv 
  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Token to authorize pushing to the repository
